# Generated by Django 3.1.4 on 2020-12-06 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=10)),
                ('poster_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TheaterMovieListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiliter_front_end_challenge.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiliter_front_end_challenge.theater')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShowtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.CharField(max_length=255)),
                ('movie_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiliter_front_end_challenge.theatermovielisting')),
            ],
        ),
    ]
